apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: web-tls
  namespace: istio-ingress
spec:
  secretName: web-tls
  duration: 2160h    # 90d
  renewBefore: 360h  # 15d
  commonName: web.local
  dnsNames:
    - web.local
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
