# 80:20(v1:v2)
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: web
  namespace: default
spec:
  hosts:
    - "web.local"
  gateways:
    - web-gateway
  http:
    - match:
        - uri:
            exact: /
        - uri:
            exact: /healthz
      route:
        - destination:
            host: web
            subset: v1
            port:
              number: 80
          weight: 80
        - destination:
            host: web
            subset: v2
            port:
              number: 80
          weight: 20
