apiVersion: v1
kind: ConfigMap
metadata:
  name: web-v1-nginx
  namespace: default
  labels:
    app: web
    version: v1
data:
  default.conf: |
    server {
      listen 80;
      server_name _;

      location = / {
        default_type application/json;
        return 200 '{"app":"istio app","version":"1.0"}';
      }

      location = /healthz {
        default_type text/plain;
        return 200 'ok';
      }
    }
